### PR TITLE
[fix] 707 modale ui

### LINKED ISSUE #707: [modale] UI revision

### PR DESCRIPTION
**Pull request by jeremie-lucca**
- Improve UI 
- Add content scroll with automatic height
- Fix responsive issues

chrome_2019-07-26_18-04-54

---------

fixes #707

### CODE REVIEW

**Comment by LuccaIntegration** [comment]
Travis automatic deployment: https://715-pr-lucca-front-LuccaSA.surge.sh

File: packages/ng/libraries/core/src/lib/overlay/sidepanel/sidepanel-panel.component.ts [hunk 1]
```diff
@@ -10,6 +10,7 @@ import { ALuModalPanelComponent } from '../modal/index';
 	selector: 'lu-sidepanel-panel',
 	templateUrl: './sidepanel-panel.component.html',
 	styleUrls: ['./sidepanel-panel.component.scss'],
+	host: {'class': 'lu-sidepanel-panel'},
```
Comment (lucienbertin) [inline packages/ng/libraries/core/src/lib/overlay/sidepanel/sidepanel-panel.component.ts]: i think the `host` atribute is deprecated and supposed to disappear in favor of `@HostBinding` decorator
